spring:
  application:
    name: kupanga
  profiles:
    active: dev
  config:
    import: optional:file:.env.dev[.properties]

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  websocket:
    allowed-origins: "http://localhost:4200 , https://kupanga.lespacelibellule.com"

server:
  port: 8089

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

email:
  sender: "no-reply@kupanga.com"

app:
  feature-flags:
    newFeature: false

jwt:
  secret-key: ${JWT_SECRET_KEY}
  expiration-time: 300000