spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/kupanga_test
    username: kupanga
    password: testpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop
        format_sql: true
  flyway:
    enabled: false
  cache:
    type: none

minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin

app:
  url: http://localhost:4200/
  reset-link: http://localhost:4200/auth/reset-password?token=
  url-login: http://localhost:4200/auth/login
  url-mino: http://localhost:9000
  cookie:
    secure: false
    same-site: Lax